name: CI deployments
on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        contract: [
          "src/ZeroExOrderBookFlashBorrower.sol:ZeroExOrderBookFlashBorrower"
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Report public key to make it easy to send funds for deployments
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cast wallet address "${PRIVATE_KEY}"
      - name: Forge deploy contract to mumbai(wip)
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        run: forge create --rpc-url "${RPC_URL}" --private-key "${PRIVATE_KEY}" --etherscan-api-key "${ETHERSCAN_KEY}" --verify ${{ matrix.contract }}
