name: CI deployments
on: [push] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Print the input name to STDOUT
        run: echo The orderbook is 0x00fb875f4d86c9c73e0176a6d244047a069ce53d